"""extend article model

Revision ID: 1a667e76fd1e
Revises: 2ea8145d0bfe
Create Date: 2026-08-23 08:36:21.481722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a667e76fd1e'
down_revision: Union[str, Sequence[str], None] = '2ea8145d0bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "articles",
        sa.Column(
            "slug",
            sa.String(length=300),
            nullable=True,
        ),
    )

    op.add_column(
        "articles",
        sa.Column(
            "meta_description",
            sa.String(length=500),
            nullable=True,
        ),
    )

    op.add_column(
        "articles",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "articles",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_articles_affiliate_program_id"),
        "articles",
        ["affiliate_program_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_articles_slug"),
        "articles",
        ["slug"],
        unique=True,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_affiliate_program_id'), table_name='articles')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'created_at')
    op.drop_column('articles', 'meta_description')
    op.drop_column('articles', 'slug')
    # ### end Alembic commands ###
