"""add blog memberships table

Revision ID: 911b5324d990
Revises: 96ca577f8d2e
Create Date: 2026-08-27 18:55:31.372555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911b5324d990'
down_revision: Union[str, Sequence[str], None] = '96ca577f8d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blog_id', name='uq_blog_memberships_user_blog')
    )
    op.create_index(op.f('ix_blog_memberships_blog_id'), 'blog_memberships', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blog_memberships_id'), 'blog_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_blog_memberships_user_id'), 'blog_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_memberships_user_id'), table_name='blog_memberships')
    op.drop_index(op.f('ix_blog_memberships_id'), table_name='blog_memberships')
    op.drop_index(op.f('ix_blog_memberships_blog_id'), table_name='blog_memberships')
    op.drop_table('blog_memberships')
    # ### end Alembic commands ###
