"""extend affiliate program

Revision ID: e688907d8f91
Revises: 6a510bb19e92
Create Date: 2026-08-21 21:41:27.494858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e688907d8f91'
down_revision: Union[str, Sequence[str], None] = '6a510bb19e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_programs', sa.Column('reward_amount', sa.Float(), nullable=True))
    op.add_column('affiliate_programs', sa.Column('reward_type', sa.String(length=50), nullable=True))
    op.add_column('affiliate_programs', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('affiliate_programs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('affiliate_programs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('affiliate_programs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_programs', 'updated_at')
    op.drop_column('affiliate_programs', 'created_at')
    op.drop_column('affiliate_programs', 'description')
    op.drop_column('affiliate_programs', 'status')
    op.drop_column('affiliate_programs', 'reward_type')
    op.drop_column('affiliate_programs', 'reward_amount')
    # ### end Alembic commands ###
